Import all the required libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

Load the data

In [2]:
tips_df = sns.load_dataset('tips')
tips_df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
tips_df.shape

(244, 7)

In [4]:
tips_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

Data Split into input features (X) and target variable (Y)

In [5]:
# X => independent feature
X = tips_df[['total_bill']]
# y => target feature
y = tips_df['tip']

X.head()

   total_bill
0       16.99
1       10.34
2       21.01
3       23.68
4       24.59

In [6]:
y.head()

0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
Name: tip, dtype: float64

Data Split into training and testing set

Training set is used to learn the relationships.

Testing set is used to evaluate how well the model performs on unseen data.

random_state is used to produce similar set of samples every time when we run the code

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape

(195, 1)

In [8]:
X_test.shape

(49, 1)

Model Training

In [9]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [10]:
coefficient = model.coef_
intercept = model.intercept_

print(coefficient)

[0.10696371]

In [11]:
print(intercept)

0.925235558557056

Model Predictions

In [12]:
y_pred = model.predict(X_test)
y_pred

array([3.04525623, 1.86330727, 3.55119456, 3.69452593, 2.31576375,
       2.83881627, 3.96728338, 2.26014262, 2.50615915, 2.57033737,
       2.88160176, 2.07723468, 2.06439904, 2.47407003, 2.00236009,
       2.91903905, 2.92652651, 3.23351235, 2.68478854, 5.33107064,
       3.13831465, 3.13403611, 2.4558862 , 1.94673896, 3.16077703,
       2.17564129, 2.02375283, 3.62927807, 2.68906708, 6.07767732,
       4.99734388, 1.75313465, 2.83025918, 3.09552917, 2.74040966,
       3.50092162, 2.21200895, 5.53644096, 2.33287794, 3.35010279,
       2.04942412, 2.47834858, 3.48701634, 2.03017065, 2.03124029,
       1.25361414, 2.05798121, 2.92438724, 1.73388118])

Comparison between actual and predicted values

In [13]:
comparison = pd.DataFrame({
    'actual_tip': y_test,
    'predicted_tip': y_pred
})

comparison

     actual_tip  predicted_tip
24         3.18       3.045256
6          2.00       1.863307
153        2.00       3.551195
211        5.16       3.694526
198        2.00       2.315764
176        2.00       2.838816
192        2.56       3.967283
124        2.52       2.260143
9          3.23       2.506159
101        3.00       2.570337
45         3.00       2.881602
233        1.47       2.077235
117        1.50       2.064399
177        2.00       2.474070
82         1.83       2.002360
146        1.36       2.919039
200        4.00       2.926527
15         3.92       3.233512
66         2.47       2.684789
142        5.00       5.331071
33         2.45       3.138315
19         3.35       3.134036
109        4.00       2.455886
30         1.45       1.946739
186        3.50       3.160777
120        2.31       2.175641
10         1.71       2.023753
73         5.00       3.629278
159        2.00       2.689067
156        5.00       6.077677
112        4.00       4.997344
218        1.44       1.753135
25         2.34       2.830259
60         3.21       3.095529
18         3.50       2.740410
119        2.92       3.500922
97         1.50       2.212009
197        5.00       5.536441
139        2.75       2.332878
241        2.00       3.350103
75         1.25       2.049424
127        2.00       2.478349
113        2.55       3.487016
16         1.67       2.030171
196        2.00       2.031240
67         1.00       1.253614
168        1.61       2.057981
38         2.31       2.924387
195        1.44       1.733881

Model Evaluation

In [14]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
mse = mean_squared_error(y_test, y_pred)
print(mse)

0.5688142529229536

In [15]:
mae = mean_absolute_error(y_test, y_pred)
print(mae)

0.6208580000398983

R^2 Metrics

R^2 = 0 => the model explains none of the variation

R^2 = 1 -> the model explains all the variation

Values between 0 and 1 indicates partial explanation of the model.

In [16]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(r2)

0.5449381659234664

Save your model

In [17]:
import pickle
with open('model.pkl', 'wb') as f:
  pickle.dump(model, f)

print('Model Saved Successfully')

Model Saved Successfully

In [18]:
with open('model.pkl', 'rb') as f:
  loaded_model = pickle.load(f)

pred = loaded_model.predict(X_test)
pred

array([3.04525623, 1.86330727, 3.55119456, 3.69452593, 2.31576375,
       2.83881627, 3.96728338, 2.26014262, 2.50615915, 2.57033737,
       2.88160176, 2.07723468, 2.06439904, 2.47407003, 2.00236009,
       2.91903905, 2.92652651, 3.23351235, 2.68478854, 5.33107064,
       3.13831465, 3.13403611, 2.4558862 , 1.94673896, 3.16077703,
       2.17564129, 2.02375283, 3.62927807, 2.68906708, 6.07767732,
       4.99734388, 1.75313465, 2.83025918, 3.09552917, 2.74040966,
       3.50092162, 2.21200895, 5.53644096, 2.33287794, 3.35010279,
       2.04942412, 2.47834858, 3.48701634, 2.03017065, 2.03124029,
       1.25361414, 2.05798121, 2.92438724, 1.73388118])