Import all the required modules

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
cust_data = pd.read_excel('/content/customers.xlsx')
prod_data = pd.read_excel('/content/products.xlsx')
purch_data = pd.read_excel('/content/purchases.xlsx')

In [3]:
cust_data.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

In [4]:
prod_data.head()

   Unnamed: 0  id                           product    cost   company
0           0   1              Liners - Baking Cups   $6.36  Skipfire
1           1   2        Nori Sea Weed - Gold Label  $85.74   Dynazzy
2           2   3                Bar Bran Honey Nut  $65.40      Ntag
3           3   4        Soup - Campbells Beef Stew  $68.16  Photojam
4           4   5  Wine - Shiraz Wolf Blass Premium  $87.39      Eare

In [5]:
purch_data.head()

,Unnamed: 0,id,purch_date,customer_num,product_num,amount,paid
0,0,1,2019-01-03 00:00:00,823,27,12,$568.92
1,1,2,2019-01-03 00:00:00,606,28,14,$395.36
2,2,3,2019-01-03 00:00:00,955,9,17,$510.17
3,3,4,2019-01-03 00:00:00,577,19,3,$68.49
4,4,5,2019-01-03 00:00:00,429,8,18,$759.42

Basic Data Cleaning

1. Drop Unnamed:0 and id specific column in the above files.
2. Check the dtype of each column and if there is any inconsistency, handle that [specifically handle cost and paid column and convert them to float type].

In [6]:
purch_data.dtypes

Unnamed: 0       int64
id               int64
purch_date      object
customer_num     int64
product_num      int64
amount           int64
paid            object
dtype: object

In [7]:
purch_data = purch_data.drop("Unnamed: 0", axis=1)
prod_data = prod_data.drop("Unnamed: 0", axis=1)

prod_data['cost']=prod_data['cost'].str.replace(r'[\$,]','',regex=True)
prod_data['cost']=prod_data['cost'].astype(float)

purch_data["paid"] = purch_data["paid"].replace(r"[\$,]", "", regex=True).astype(float)
purch_data["amount"] = purch_data["amount"].astype(float)

purch_data["purch_date"]=pd.to_datetime(purch_data["purch_date"])

In [8]:
cust_data.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

In [9]:
purch_data

        id purch_date  customer_num  product_num  amount    paid
0        1 2019-01-03           823           27    12.0  568.92
1        2 2019-01-03           606           28    14.0  395.36
2        3 2019-01-03           955            9    17.0  510.17
3        4 2019-01-03           577           19     3.0   68.49
4        5 2019-01-03           429            8    18.0  759.42
...    ...        ...           ...          ...     ...     ...
5995  5996 2019-06-20           893           33     5.0  411.10
5996  5997 2019-06-20           566           23    11.0  178.97
5997  5998 2019-06-20           114           19     9.0  205.47
5998  5999 2019-06-20           404           11    20.0  429.40
5999  6000 2019-06-20            88           57     4.0  274.52

[6000 rows x 6 columns]

In [10]:
prod_data

    id                             product   cost       company
0    1                Liners - Baking Cups   6.36      Skipfire
1    2          Nori Sea Weed - Gold Label  85.74       Dynazzy
2    3                  Bar Bran Honey Nut  65.40          Ntag
3    4          Soup - Campbells Beef Stew  68.16      Photojam
4    5    Wine - Shiraz Wolf Blass Premium  87.39          Eare
5    6  Wine - White, Riesling, Semi - Dry  99.22      Livepath
6    7                        Brandy - Bar  13.83          Oloo
7    8                      Onions - White  42.19          Oozz
8    9         Lettuce - Baby Salad Greens  30.01        Meevee
9   10                Sambuca - Ramazzotti  88.99      Livepath
10  11                Coffee - Decafenated  21.47        Meezzy
11  12             Lamb Leg - Bone - In Nz  42.56     Photofeed
12  13                Lettuce - Spring Mix  19.90  Twitterworks
13  14              Cookies Oatmeal Raisin  99.40       Dynabox
14  15              Cookies Oatmeal Raisin  14.13          Vitz
15  16                   Sausage - Chorizo  55.45           NaN
16  17                     Glaze - Apricot  33.78    Browsezoom
17  18                           Squid Ink  56.33         Aibox
18  19               Loaf Pan - 2 Lb, Foil  22.83   Brainsphere
19  20        Bagel - Everything Presliced  87.05        Trunyx
20  21          Bagel - Whole White Sesame  90.48      Realcube
21  22                 Scotch - Queen Anne  60.26           NaN
22  23                Puree - Blackcurrant  16.27       Zoombox
23  24               Bread - Bagels, Plain  31.26          Vitz
24  25               Snapple Raspberry Tea  73.70       Innojam
25  26               Sour Puss - Tangerine  84.20       Skinder
26  27                    Spaghetti Squash  47.41           NaN
27  28         Wine - Niagara,vqa Reisling  28.24           NaN
28  29                Iced Tea Concentrate  59.23     Photolist
29  30                         Fuji Apples  22.96       Cogibox
30  31      Wine - Carmenere Casillero Del  55.77          Ntag
31  32                Container Clear 8 Oz  92.33          Muxo
32  33                         Duck - Legs  82.22       Voonder
33  34            Muffin Hinge Container 6  99.54        Skyble
34  35          Pie Box - Cello Window 2.5  95.68      Linkbuzz
35  36              Bread - English Muffin  13.83         Quatz
36  37    Chocolate - Sugar Free Semi Choc  61.99     Realpoint
37  38                   Pate - Peppercorn  21.98         Mynte
38  39             Triple Sec - Mcguinness  37.45         Oodoo
39  40                  Pepper - Cubanelle  79.31       Cogibox
40  41                      Squash - Acorn  65.35         Meemm
41  42                  Sauce - Demi Glace  87.51      Wordware
42  43                   Pail For Lid 1537  40.69      Edgeclub
43  44                        Foam Tray S2  30.67  Jabbersphere
44  45                        Shark - Loin  45.77  Thoughtstorm
45  46            Aromat Spice / Seasoning  61.34           NaN
46  47                       Tobasco Sauce  48.32    Browsezoom
47  48           Apple - Delicious, Golden  36.67         Skiba
48  49                         Lamb - Rack  62.60         Gevee
49  50              Silicone Paper 16.5x24  63.98    Babbleopia
50  51               Ecolab - Power Fusion  75.32      Fliptune
51  52          Soup - Knorr, Country Bean  98.74        Eimbee
52  53            Chicken - Thigh, Bone In  74.06   Topiclounge
53  54      Plate - Foam, Bread And Butter  37.79     Flipstorm
54  55                     Beef - Bresaola   8.55      Digitube
55  56                       Peach - Fresh  20.53         Zazio
56  57                 Muffin Hinge - 211n  68.63      Fanoodle
57  58                  Bar Bran Honey Nut  73.05        Yakijo
58  59       Nut - Almond, Blanched, Whole  74.28         Eazzy
59  60            Table Cloth 90x90 Colour  41.22         Quinu

idxmax()

Find the index of the maximum value in the 'paid' column

In [11]:
index_max_paid = purch_data['paid'].idxmax()
print(index_max_paid)

211

GROUP BY Function

Evaluate the average cost of products per company

In [15]:
group_by_company=prod_data.groupby('company')
avg_amount_per_product = group_by_company['cost'].mean()
print(avg_amount_per_product)

company
Aibox           56.330
Babbleopia      63.980
Brainsphere     22.830
Browsezoom      41.050
Cogibox         51.135
Digitube         8.550
Dynabox         99.400
Dynazzy         85.740
Eare            87.390
Eazzy           74.280
Edgeclub        40.690
Eimbee          98.740
Fanoodle        68.630
Flipstorm       37.790
Fliptune        75.320
Gevee           62.600
Innojam         73.700
Jabbersphere    30.670
Linkbuzz        95.680
Livepath        94.105
Meemm           65.350
Meevee          30.010
Meezzy          21.470
Muxo            92.330
Mynte           21.980
Ntag            60.585
Oloo            13.830
Oodoo           37.450
Oozz            42.190
Photofeed       42.560
Photojam        68.160
Photolist       59.230
Quatz           13.830
Quinu           41.220
Realcube        90.480
Realpoint       61.990
Skiba           36.670
Skinder         84.200
Skipfire         6.360
Skyble          99.540
Thoughtstorm    45.770
Topiclounge     74.060
Trunyx          87.050
Twitterworks    19.900
Vitz            22.695
Voonder         82.220
Wordware        87.510
Yakijo          73.050
Zazio           20.530
Zoombox         16.270
Name: cost, dtype: float64

Summarization

1. Pivot Tables: It is a powerful tool that allows us to summarize and aggregate data in a flexible and customizable way.

2. CrossTab: In Pandas, it is used to compute a simple cross tabulation of two factors. It is similar to pivot tables but focuses on counting the frequencies.

3. Melting

1. index: array-like, Series, or list of arrays/Series
Values to group by in the rows.
Multiple index values can also be provided for multi-level indexing index=['Region', 'Product']
2. columns: array-like, Series, or list of arrays/Series
Values to group by in the columns.
3. values: array-like, optional
Array of values to aggregate.
4. aggfunc: function, optional, default numpy.mean
Multiple aggregation function can be used;  aggfunc=[sum, 'mean'].

In [20]:
# sample data
data = {
    'region': ['east', 'west', 'east', 'west', 'east', 'west', 'east'],
    'product': ['A', 'A', 'B', 'B', 'C', 'C', 'B'],
    'sales': [100, 150, 200, 250, 300, 350, 100]
    }

data = pd.DataFrame(data)
# creating a pivot table
pivot_table = data.pivot_table(values = 'sales', index = 'region', columns = 'product', aggfunc='sum')
print(pivot_table)

product    A    B    C
region
east     100  300  300
west     150  250  350

In [22]:
# sample data
data = {
    'region': ['east', 'west', 'east', 'west', 'east', 'west', 'east'],
    'product': ['A', 'A', 'B', 'B', 'C', 'C', 'B'],
    'sales': [100, 150, 200, 250, 300, 350, 100]
    }

data = pd.DataFrame(data)
# creating a crosstab
crosstab = pd.crosstab(data['region'], data['product'])
print(crosstab)

product  A  B  C
region
east     1  2  1
west     1  1  1

In [23]:
data = {
    'region': ['east', 'west'],
    'prod_A': [100, 150],
    'prod_B': [200, 250],
    'prod_C': [300, 350]
}

df = pd.DataFrame(data)
melted_df = pd.melt(df, id_vars=['region'], value_vars=['prod_A', 'prod_B', 'prod_C'], var_name='Product', value_name='Sales')
print(melted_df)

  region Product  Sales
0   east  prod_A    100
1   west  prod_A    150
2   east  prod_B    200
3   west  prod_B    250
4   east  prod_C    300
5   west  prod_C    350

Save all the files

In [24]:
prod_data.to_excel('products_cleaned.xlsx', index=False)
purch_data.to_excel('purchases_cleaned.xlsx', index=False)